version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.2-management
    restart: always
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    