GET http://127.0.0.1:8000/api HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDk5MTk0Nzl9.sCGF1SVELJDkF4D3s0UBlhmVaYwQrldrhNVb9JTxfFE

###
POST http://127.0.0.1:8000/api/signup HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn123@gmail.com",
    "password": "asd123"
}

###
POST http://127.0.0.1:8000/api/signin HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn123@gmail.com",
    "password": "asd123"
}